CREATE TABLE IF NOT EXISTS DM_DEVICE_ORGANIZATION (
    ID                     INTEGER auto_increment NOT NULL,
    DEVICE_ID              INT(11) DEFAULT NULL,
    PARENT_DEVICE_ID       INT(11) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_DM_DEVICE_DM_ID FOREIGN KEY (DEVICE_ID)
    REFERENCES DM_DEVICE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
    CONSTRAINT fk_DM_DEVICE_DM_ID2 FOREIGN KEY (PARENT_DEVICE_ID)
    REFERENCES DM_DEVICE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
    );